// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABm9KiY88EjZNCPkISCOzs5vNU_sygTSo',
    appId: '1:505823824624:android:dcc6088fe5db32d8281035',
    messagingSenderId: '505823824624',
    projectId: 'wechat-e9958',
    storageBucket: 'wechat-e9958.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHPpLhY7_XudSZda1Jscwj2ITEGfJANtA',
    appId: '1:505823824624:ios:6fafb0eb78fa5635281035',
    messagingSenderId: '505823824624',
    projectId: 'wechat-e9958',
    storageBucket: 'wechat-e9958.firebasestorage.app',
    androidClientId: '505823824624-7cldjhflp02sqtng6g00n9o70cb0k83v.apps.googleusercontent.com',
    iosClientId: '505823824624-ifsm3ihk27i0sf2avt93rejsb51c0rvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

}